FROM node:22-alpine

RUN npm install -g pnpm

USER user
WORKDIR /app
EXPOSE 3000

COPY ./vite-react-template/package*.json ./
RUN npm install 

COPY ./vite-react-template ./
RUN npm run build

CMD ["npm", "run", "preview"]