FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

EXPOSE 3000

COPY ./vite-react-template/package*.json .
COPY ./vite-react-template .

RUN npm install && \
		npm run build && \
		npm cache clean --force && \ 
		rm -rf /root/.npm && \ 
		rm -rf node_modules
		
CMD ["npm", "run", "preview"]