FROM node:22 AS builder

USER user
WORKDIR /app

COPY ./vite-react-template/package*.json .
RUN npm install

COPY ./vite-react-template .
RUN npm run build

FROM nginx:stable-alpine3.23
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]